color0 #212431
color1 #fd4663
color2 #899bea
color3 #ac90e3
color4 #cf97dc
color5 #93a3ec
color6 #b296e9
color7 #f2f2f3
color8 #616677
color9 #fd4663
color10 #899bea
color11 #ac90e3
color12 #cf97dc
color13 #93a3ec
color14 #b296e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #191b24
background            #191b24
foreground            #f2f2f3
selection_foreground  #afb0b6
selection_background  #212431
active_border_color   #899bea
inactive_border_color #212431
url_color             #899bea

active_tab_foreground   #11131b
active_tab_background   #899bea
inactive_tab_foreground #afb0b6
inactive_tab_background #212431
cursor_trail_color      #afb0b6
